#Configuration for a application with the name "config-client"

config-client:
  value: default

some:
  property: "config-client property file! Ik ben geupdated!"

management:
  security:
      enabled: false
