#Configuration for a application with the name "config-client"

config-client:
  value: default

some:
  property: "config-client property file, ik ben geupdate!"

management:
  server:
    port: 30000
  security:
      enabled: false
