#Configuration for a application with the name "config-client"

config-client:
  value: changed to other value

some:
  property: "config-client property file!"

management:
  security:
      enabled: false
